### ISSUE TITLE
Best way to help?

### ISSUE THREAD

**Issue by differentsmoke** [massif-press/lancer-data#101]
I'm interested in helping to update the lancer-data to the latest version. What would be the best way of helping out?

(I don't have much experience using GH for open source collaboration, so apologies if this is a weird way of reaching out.)

Thanks.

**Comment by aritsune** [comment]
@differentsmoke We're working on doing the update via a script that parses the book, so I'm afraid there's not much room to help there. If you want to help with the comp/con app you can hit us up on Discord in the #compcon channel in the LANCER server: https://discord.gg/rwcpzsU
