### ISSUE TITLE
Bug Report: Squad NPC statistics

### ISSUE THREAD

**Issue by jarena3** [massif-press/lancer-data#116]
<strong>Submitted At: </strong>3/8/2020 0:54:13
<strong>Item: </strong>Squad NPC statistics
<strong>Incorrect Text: </strong>App has wrong ranges/damage/rules text for the infantry Primary and Anti-Armor Weapons
<strong>Correct Text/Ref: </strong>Core rulebook, pg. 323
<strong>Contact Info: </strong>magichateball#0420 on discord

**Comment by Eranziel** [comment]
Looks like a report from CC 1.X. Squad primary and anti-armor weapons in 2.0.21 match current rules text.
