### ISSUE TITLE
You Can Use the UNCLE class Comp Con/Mods with the Gravity Gun?

### ISSUE THREAD

**Issue by Surrealaser** [massif-press/lancer-data#127]
Perhaps the wording actually means that it just cannot be modified by core bonuses, but in the event that the Gravity Gun cannot be subject to mods, thought I'd point this out.

**Comment by Piezoelectric** [comment]
Tom clarified that you cannot UNCLE Gravity Gun or apply any other weapon mods. The Comp/Con app *should* handle this already, though I'd need to check
