### ISSUE TITLE
[BUG] Tactician I/II (Opportunist/Solar Backdrop) tooltip inconsistency

### ISSUE THREAD

**Issue by samoreGE** [massif-press/lancer-data#179]
**Describe the bug**
Opportunist has a tooltip on melee weapons, but Solar Backdrop doesn't have a tooltip on ranged weapons.

**To Reproduce**
1. Make a Pilot with the first two Tactician talent tiers
2. Make a mech with both ranged and melee weapons
3. Observe what the Opportunist tooltip under the melee weapon, and the lack of Solar Backdrop tooltip on the ranged weapon.

**Expected behavior**
Either both talents should have tooltips, or neither talent should have one.

**Screenshots**
![image](https://user-images.githubusercontent.com/55170045/187799433-253e387c-7764-4227-ba29-0343fa273837.png)
![image](https://user-images.githubusercontent.com/55170045/187799381-a632f4ec-0dd7-471e-a5f4-df02caa46e5c.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version 104.0.5112.102

**Comment by msprijatelj** [comment]
Issue is due to a typo in `weapon_types` in Lancer-Data. Need to replace "Ranged" in the `weapon_types` field for Tactician 2 with all of the other weapon types (which are definitively not Melee). Going to move this to lancer-data
