### ISSUE TITLE
Bug Report: Operator NPC, Step Trait

### ISSUE THREAD

**Issue by jarena3** [massif-press/lancer-data#40]
<strong>Submitted At: </strong>7/12/2019 22:15:22
<strong>Item: </strong>Operator NPC, Step Trait
<strong>Incorrect Text: </strong>Step trait lacks the recharge tag
<strong>Correct Text/Ref: </strong>Step trait should have "Recharge (5+), LANCER core rulebook pp. 425
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
It has it, recharge was just not being displayed correctly in the NPC builder.
