### ISSUE TITLE
Bug Report: The Lesson of the Held Image, HORUS core bonus

### ISSUE THREAD

**Issue by jarena3** [massif-press/lancer-data#54]
<strong>Submitted At: </strong>7/18/2019 18:39:51
<strong>Item: </strong>The Lesson of the Held Image, HORUS core bonus
<strong>Incorrect Text: </strong>Once a round, at the start of any ally’s turn, you can make a Lock On tech attack against any character in your sensor range as a reaction to your ally’s turn starting.
<strong>Correct Text/Ref: </strong>Once a round, at the start of any ally’s turn, you can make a Lock On tech action against any character in your sensor range as a reaction to your ally’s turn starting.
<strong>Contact Info: </strong>

**Comment by CommanderTso** [comment]
Fixed in PR #57.
