### ISSUE TITLE
Bug Report: GMS Nexuses (nexii???)

### ISSUE THREAD

**Issue by jarena3** [massif-press/lancer-data#56]
<strong>Submitted At: </strong>7/22/2019 2:42:33
<strong>Item: </strong>GMS Nexuses (nexii???)
<strong>Incorrect Text: </strong>Both gms nexuses (light and hunter-killer) currently are called drone nexuses
<strong>Correct Text/Ref: </strong>They should simply be Nexus (Light) and Nexus (Hunter-Killer)
<strong>Contact Info: </strong>

**Comment by CommanderTso** [comment]
@jarena3 Can't find anything in either lancer-data or in reviewing the master branch of compcon that shows the incorrect spelling. Was this already fixed?

**Comment by jarena3** [comment]
it looks like they mean just the GMS weapon names, not the types. I'll make that change now
